name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'microsoft'

    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 12266803
        accept-android-sdk-licenses: true
        log-accepted-android-sdk-licenses: true
        packages: |
          platform-tools
          build-tools;34.0.0
          platforms;android-34

    - name: Install Xamarin.Android workload
      run: |
        dotnet workload install android

    - name: Restore NuGet packages
      run: dotnet restore WoWonder.csproj

    - name: Build Debug APK
      run: |
        dotnet build WoWonder.csproj -c Debug -p:AndroidBuildApplicationPackage=true

    - name: Build Release APK
      run: |
        dotnet build WoWonder.csproj -c Release -p:AndroidBuildApplicationPackage=true

    - name: Build AAB (Android App Bundle)
      run: |
        dotnet build WoWonder.csproj -c Release -p:AndroidBuildApplicationPackage=true -p:AndroidPackageFormat=aab

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: |
          bin/Debug/**/*.apk
          bin/Debug/**/*-Signed.apk

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: |
          bin/Release/**/*.apk
          bin/Release/**/*-Signed.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: android-app-bundle
        path: |
          bin/Release/**/*.aab

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          Automated release of Handshakes4u Social Community app
          
          ## Downloads
          - APK: Available in the artifacts section
          - AAB: Available in the artifacts section
        draft: false
        prerelease: false
        files: |
          bin/Debug/**/*.apk
          bin/Release/**/*.apk
          bin/Release/**/*.aab
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 