name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'microsoft'

    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        accept-android-sdk-licenses: true
        log-accepted-android-sdk-licenses: true
        packages: "platform-tools build-tools;34.0.0 platforms;android-34"

    - name: Install Android workload
      run: |
        echo "=== Installing Android workload ==="
        dotnet workload install android --include-previews
        echo "=== Verifying installation ==="
        dotnet workload list | grep -i android || echo "Android workload not found"
        
    - name: Verify environment
      run: |
        echo "=== .NET SDK Version ==="
        dotnet --version
        echo "=== Installed Workloads ==="
        dotnet workload list
        echo "=== Available SDKs ==="
        dotnet --list-sdks
        echo "=== Available Runtimes ==="
        dotnet --list-runtimes
        echo "=== Android SDK Location ==="
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"

    - name: Restore NuGet packages
      run: dotnet restore WoWonder.csproj

    - name: Build Debug APK
      run: |
        dotnet build WoWonder.csproj -c Debug -p:AndroidBuildApplicationPackage=true

    - name: Build Release APK
      run: |
        dotnet build WoWonder.csproj -c Release -p:AndroidBuildApplicationPackage=true

    - name: Build AAB (Android App Bundle)
      run: |
        dotnet build WoWonder.csproj -c Release -p:AndroidBuildApplicationPackage=true -p:AndroidPackageFormat=aab

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: |
          bin/Debug/**/*.apk
          bin/Debug/**/*-Signed.apk

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: |
          bin/Release/**/*.apk
          bin/Release/**/*-Signed.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: android-app-bundle
        path: |
          bin/Release/**/*.aab

    - name: Build Summary
      run: |
        echo "🎉 Build completed successfully!"
        echo "📱 APK files are available in the artifacts section"
        echo "📦 AAB files are available in the artifacts section"
        echo ""
        echo "To create a release manually:"
        echo "1. Go to the Actions tab"
        echo "2. Download the artifacts"
        echo "3. Go to Releases and create a new release"
        echo "4. Upload the APK/AAB files" 